const TYPES = {
   GET_POKEMON_LIST: "GET_POKEMON_LIST",
   GET_NEXT_POKEMON_LIST: "GET_NEXT_POKEMON_LIST",
   GET_POKEMON_DETAIL: "GET_POKEMON_DETAIL",
   GET_MY_POKEMON_LIST: "GET_MY_POKEMON",
   REMOVE_POKEMON: "REMOVE_POKEMON",
};

export { TYPES };
